### ISSUE TITLE
any chance of an ubuntu build?

### ISSUE THREAD

**Issue by popebrak** [USU-Security/ipvisualizer#1]
Hi there. I saw this project on display at the LISA 14 conference and was really impressed. I've been trying to compile it on Ubuntu 14.04, but with no luck:

display.c:27:21: fatal error: SDL/SDL.h: No such file or directory
 #include <SDL/SDL.h>

You mention in the readme that somebody should remind you to build for ubuntu again. Any chance I might be that someone?

Cheers.

**Comment by dballing** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

That seems like just a missing set of library/headers.... Do you have
the SDL (and its devel headers) installed?

Disclaimer: I am a lurker who has never even compiled this thing yet. :-
)

D

On 4/17/2015 12:14 PM, popebrak wrote:

> Hi there. I saw this project on display at the LISA 14 conference
> and was really impressed. I've been trying to compile it on Ubuntu
> 14.04, but with no luck:
> 
> display.c:27:21: fatal error: SDL/SDL.h: No such file or directory 
> #include
> 
> You mention in the readme that somebody should remind you to build
> for ubuntu again. Any chance I might be that someone?
> 
> Cheers.
> 
> — Reply to this email directly or view it on GitHub 
> https://github.com/USU-Security/ipvisualizer/issues/1.

---

I prefer to use encrypted mail. My public key fingerprint is FD6A 6990
F035 DE9E 3713 B4F1 661B 3AD6 D82A BBD0. You can download it at
http://www.megacity.org/gpg_dballing.txt

Learn how to encrypt your email with the E-Mail Self Defense Guide:
https://emailselfdefense.fsf.org/en/
-----BEGIN PGP SIGNATURE-----
Version: GnuPG/MacGPG2 v2.0
Comment: GPGTools - https://gpgtools.org

iQIcBAEBCgAGBQJVMTXxAAoJEGYbOtbYKrvQ8VsP/1ByUuUSqRKbMZfdqcg87TAc
kW64KtdVxmc3y8vx6f/9aRoIz3tU7FdmG+Z0HSUNJtyTzb3vtiY7xrPqJ+pE2kP4
S5naWFXed2WQf4wGwTWgy8aasDeZjTP4FtpkqIZQswFW+p50a/uT/rvQlaxsjp8M
a0M4j8SzI+FswzTMXOR8EUL7hpf3mQXtSpmIJ2wSUteLVdCgyP8gedK+6j0lEBwS
xH6gaOe8tSh7NVcwnyTSfe/UAASCU2TlEWj69XYE6vxwvpYkfeyvlCHrBljyEUSM
+6vnFOu93q++6fwpKsLpmq1ghZpeLfPKS4kqmKA8lhvHkDNKPZ8hUGdpMZyrTeYA
xiqrVGJ4O1vnSu23B6b9C1n6p/tjrFVMPVUbQX7KFeJmA3aUbdtawod/QP2P/obX
w1EUwRLY3dQdbvHAZscPVWT/IX2p3qYZrvY9kM4+rlK1WEaUoXgtrys4TqeuT5P/
9jG3ILTC43XJHEcwCPm4PyUlhtmJeQ12cQBhTPJmZKF40at5ZLVNKdVUPEMM7Bdr
oOmG1iIwuEpK8g4xhG0arQxCkB+K8fI9/+cTjepkR5DxeFEi9PYHmO4Aj1727dlL
cJUtLKvgMnKr55g22m8cSRlT616MukCmCalyL5RpDv3hYmFCo9wJcSp3kpOg8os1
PPxhdAhao0KBVA4QrwBi
=CtRp
-----END PGP SIGNATURE-----

**Comment by ekoyle** [comment]
dballing is correct, it looks like you might need to install libsdl1.2-dev (probably among other -dev packages).

I'll see if it builds trivially on ubuntu.

**Comment by popebrak** [comment]
Hi gentlemen,

Thank you kindly for the assistance. I did, indeed, neglect to install the appropriate sdl dev package, but I'm afraid I have now run into another error:

$ make
make  all-recursive
make[1]: Entering directory `/usr/local/src/ipvisualizer/ipvisualizer'
Making all in client
make[2]: Entering directory`/usr/local/src/ipvisualizer/ipvisualizer/client'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory`/usr/local/src/ipvisualizer/ipvisualizer/client'
Making all in server
make[2]: Entering directory `/usr/local/src/ipvisualizer/ipvisualizer/server'
gcc   -g -O2  -L/usr/lib/x86_64-linux-gnu -lcurl  -o ipvisualizer_flowserv ipvisualizer_flowserv-flowserv.o ipvisualizer_flowserv-fwrules.o ipvisualizer_flowserv-globals.o ipvisualizer_flowserv-sockutils.o ipvisualizer_flowserv-subnets.o ../shared/ipvisualizer_flowserv-flowdata.o ../shared/ipvisualizer_flowserv-config.o  -lpthread -lpcap -lSDL -lGLU -lGL 
ipvisualizer_flowserv-subnets.o: In function`getsubnets':
/usr/local/src/ipvisualizer/ipvisualizer/server/subnets.c:87: undefined reference to `curl_easy_setopt'
/usr/local/src/ipvisualizer/ipvisualizer/server/subnets.c:88: undefined reference to`curl_easy_setopt'
/usr/local/src/ipvisualizer/ipvisualizer/server/subnets.c:89: undefined reference to `curl_easy_setopt'
/usr/local/src/ipvisualizer/ipvisualizer/server/subnets.c:90: undefined reference to`curl_easy_setopt'
/usr/local/src/ipvisualizer/ipvisualizer/server/subnets.c:93: undefined reference to `curl_easy_perform'
/usr/local/src/ipvisualizer/ipvisualizer/server/subnets.c:78: undefined reference to`curl_easy_init'
/usr/local/src/ipvisualizer/ipvisualizer/server/subnets.c:81: undefined reference to `curl_easy_setopt'
ipvisualizer_flowserv-subnets.o: In function`cleanup':
/usr/local/src/ipvisualizer/ipvisualizer/server/subnets.c:62: undefined reference to `curl_easy_cleanup'
collect2: error: ld returned 1 exit status

It would seem as if the curl library isn't being linked, but I can plainly see the "-lcurl" string in the gcc command. And I do seem to have the appropriate libcurl development package installed. . . 

$ sudo apt-get install libcurl4-gnutls-dev
Reading package lists... Done
Building dependency tree  
Reading state information... Done
libcurl4-gnutls-dev is already the newest version.

Any thoughts? Forgive me if I'm missing something trivially apparent - I'm really not a programmer.

**Comment by ekoyle** [comment]
So I know this issue is over a year old... but I finally got around to building for ubuntu.

I am currently building for amd64 and i386 on debian: `sid`, `wheezy`, `jessie`, and `stretch` and ubuntu: `vivid`, `wily`, and `xenial`.  Let me know if there is interest in any others.

I have a `stable`, `testing`, and `unstable` repo for each, but currently there isn't much difference between them.

Example sources.list entry for `sid` and `unstable`:

```
deb http://debian.usu.edu/usu-security/ sid-security-unstable main
```

Then `apt-get update` and install `usu-archive-keyring` or run the following:

```
cat << EOF | apt-key add
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQINBFFjStsBEADITlJcbksM5Cmw9pvw9OpcOrsIzonQwQPUqc9gZwPCo1POMYi6
et9evIOgWMAPKLVlC9MMZw18UpPAdzslrlEz8gFBWmKXABonL+Qw/S3enSof0k69
f8rznTDsYiUjlJ9gZfkZosMCPVFJNzZoZaAzABIxk4jKwAAsRzcJ0zLzQJgIG5fQ
YXkTEBS3NEE+QaOm0wiOyE4ijv5NhGcf05CX6d8UzosG0sotYeYKPwDcuJCZtC6x
oVKduS7nsjLTFlopPPa0LFPvZWXjqxKLkasyk/V8EnCWzEdKA+ogQs0sf0FpZUnG
lmHxwpqQQI773BLO1yqSMBwgs6bG/lEts3kugZnui9/PMdo8lcfSxXUP3JiX+iER
2+aCEPhUuHg9SlEkLYkwpTuvZi9XLD1uV40d1ohOqTY85na2UidxuwRAYLcmAEx7
ZphHQgr4/N+TZqop3LuAYNlPAApxDQ0qOdev8Wb/5vyMI2XoexndYrNrNfy5/5d6
0V9YnieqHCmVEv27UENPCF2K29Ke/akKFpd9jpBQabHxjquqANeeTRm+TOzzIvGb
IkRxVbG9AznPq3qDTs8dE2AVa3ZtTM3EYWruEeTwBnd1/bU0nwZcYp6pADeAfEFe
2b3DKnfxt+wqyjEeP2fMvr2QZDSb9hSbM4+itJqVuQyqmgVPamxNYXyzOwARAQAB
tDltaW5pLWJ1aWxkZCBhcmNoaXZlIHVzdSA8bWluaS1idWlsZGRAa2liYmxlcy5u
Y3MudXN1LmVkdT6JAj4EEwECACgFAlFjStsCGy8FCRLMAwAGCwkIBwMCBhUIAgkK
CwQWAgMBAh4BAheAAAoJEDYeb/p0lFfmxjAQAIDhvYIj4ofK9GDpI9+MwWKBiiMq
XPbGtC9xfXOM1ygZ1s53rpmd4uKJ2BsyiL+i11FXixiTGn/Asydt3exoy8UdeeDW
9AYu1PObKzJKXouioVrHBC+GFauFIzwZt47GKueRo2f+D+gLsAvFyZF8fxsmsvYE
wlVUuet5REGbcxMTWPT+1ClaRfkBzcgYD6Rr6UYvkVKTbS9nv+ub8HLLufcsVKtu
FBWXcsttIlIxgcPEaJWLWkbSap4ktAg7BdaIqMFc7KQqu/WbSAXEYJPrDKQueed8
J9UZ/+UOVqFKvjDql+ghOqtsjGDTvxkoHM9T7kMAuzoF8rc2GDNFzsDOQ9SRhodo
xZJBEdGjM5NK1RYktrwV10gHBKP14A4GMeMabYBhJ3xJZ2Z2K1PSxi118iJpIqZA
6BJs8ylrhWoboWB2LefWs2JudLaQCS3UXk6uaBBNckSGxYgnZPsxfppdHUF5n/oJ
MFmMvatgF7f/AcdbWmcWNK7Wqbmby68Y0MqDFgwKgpVrTdMIJRthkdttel+WlQQT
08gAu7KVJNA1XvLnFnLPR3E2oNari9XXEFjhHPZ3ZLJL1l2H8Cl5uap5dH9VEsxM
vY3SFZ1rNJl1iLdVoxpoh9+DIDAF2mxaPHSeGCKnOhBd5Qvt7O0EJ9bmxq6r85kX
N/b2wICJfbYBisrB
=sx78
-----END PGP PUBLIC KEY BLOCK-----
EOF

```
